[2025-09-04T03:20:45.632+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-04T03:20:45.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.top_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T03:20:45.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.top_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T03:20:45.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-04T03:20:45.903+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): top_products> on 2025-09-03 00:00:00+00:00
[2025-09-04T03:20:45.922+0000] {standard_task_runner.py:63} INFO - Started process 2611 to run task
[2025-09-04T03:20:45.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'top_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpyerinc1i']
[2025-09-04T03:20:45.944+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask top_products
[2025-09-04T03:20:46.068+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-04T03:20:46.252+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.top_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host 6aba05baf296
[2025-09-04T03:20:46.872+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='top_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-09-04T03:20:46.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-04T03:20:46.916+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-04T03:20:46.921+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** psql -h postgres -U *** -d *** -f /opt/***/sql/top_products.sql']
[2025-09-04T03:20:46.945+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T03:20:47.268+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/top_products.sql:1: NOTICE:  table "top_products" does not exist, skipping
[2025-09-04T03:20:47.269+0000] {subprocess.py:93} INFO - DROP TABLE
[2025-09-04T03:20:47.277+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/top_products.sql:12: ERROR:  relation "transactions" does not exist
[2025-09-04T03:20:47.281+0000] {subprocess.py:93} INFO - LINE 7: FROM transactions
[2025-09-04T03:20:47.284+0000] {subprocess.py:93} INFO -              ^
[2025-09-04T03:20:47.304+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-04T03:20:47.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-04T03:20:47.394+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecommerce_pipeline, task_id=top_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20250904T032045, end_date=20250904T032047
[2025-09-04T03:20:47.539+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-04T03:20:47.581+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-04T03:20:47.639+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
