[2025-09-03T16:59:47.827+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T16:59:47.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_s3_dag.upload_file_to_s3 manual__2025-09-03T16:59:45.149485+00:00 [queued]>
[2025-09-03T16:59:47.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_s3_dag.upload_file_to_s3 manual__2025-09-03T16:59:45.149485+00:00 [queued]>
[2025-09-03T16:59:47.970+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-03T16:59:48.040+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2025-09-03 16:59:45.149485+00:00
[2025-09-03T16:59:48.064+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_to_s3_dag', 'upload_file_to_s3', 'manual__2025-09-03T16:59:45.149485+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_s3_dag.py', '--cfg-path', '/tmp/tmpim52hhis']
[2025-09-03T16:59:48.072+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask upload_file_to_s3
[2025-09-03T16:59:48.052+0000] {standard_task_runner.py:63} INFO - Started process 1660 to run task
[2025-09-03T16:59:48.127+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T16:59:48.245+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_to_s3_dag.upload_file_to_s3 manual__2025-09-03T16:59:45.149485+00:00 [running]> on host 6aba05baf296
[2025-09-03T16:59:48.540+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='upload_to_s3_dag' AIRFLOW_CTX_TASK_ID='upload_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T16:59:45.149485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T16:59:45.149485+00:00'
[2025-09-03T16:59:48.542+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T16:59:48.662+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-09-03T16:59:48.664+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-09-03T17:01:06.865+0000] {logging_mixin.py:188} INFO - âœ… File /opt/***/datasets/online_retail.csv berhasil di-upload ke s3://ecommerce-arel-retail/datasets/retail.csv
[2025-09-03T17:01:06.869+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-03T17:01:06.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T17:01:06.900+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_to_s3_dag, task_id=upload_file_to_s3, run_id=manual__2025-09-03T16:59:45.149485+00:00, execution_date=20250903T165945, start_date=20250903T165947, end_date=20250903T170106
[2025-09-03T17:01:07.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-03T17:01:07.502+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T17:01:07.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
