[2025-09-03T16:59:47.846+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T16:59:47.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_s3_conn.test_s3 manual__2025-09-03T16:59:42.775535+00:00 [queued]>
[2025-09-03T16:59:47.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_s3_conn.test_s3 manual__2025-09-03T16:59:42.775535+00:00 [queued]>
[2025-09-03T16:59:47.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-03T16:59:48.083+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_s3> on 2025-09-03 16:59:42.775535+00:00
[2025-09-03T16:59:48.102+0000] {standard_task_runner.py:63} INFO - Started process 1661 to run task
[2025-09-03T16:59:48.113+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_s3_conn', 'test_s3', 'manual__2025-09-03T16:59:42.775535+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/S3_dag.py', '--cfg-path', '/tmp/tmpf1ikaqk5']
[2025-09-03T16:59:48.128+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask test_s3
[2025-09-03T16:59:48.190+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T16:59:48.315+0000] {task_command.py:426} INFO - Running <TaskInstance: test_s3_conn.test_s3 manual__2025-09-03T16:59:42.775535+00:00 [running]> on host 6aba05baf296
[2025-09-03T16:59:48.556+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_s3_conn' AIRFLOW_CTX_TASK_ID='test_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T16:59:42.775535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T16:59:42.775535+00:00'
[2025-09-03T16:59:48.558+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T16:59:48.641+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-09-03T16:59:48.644+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-09-03T16:59:51.585+0000] {logging_mixin.py:188} INFO - Buckets: ['bucket-engineer', 'config-bucket-440173072148', 'ecommerce-arel-retail']
[2025-09-03T16:59:51.592+0000] {python.py:237} INFO - Done. Returned value was: ['bucket-engineer', 'config-bucket-440173072148', 'ecommerce-arel-retail']
[2025-09-03T16:59:51.594+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T16:59:51.676+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_s3_conn, task_id=test_s3, run_id=manual__2025-09-03T16:59:42.775535+00:00, execution_date=20250903T165942, start_date=20250903T165947, end_date=20250903T165951
[2025-09-03T16:59:52.558+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-03T16:59:52.650+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T16:59:52.668+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
