[2025-08-30T05:32:19.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-30T05:32:20.040+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-29T00:00:00+00:00 [queued]>
[2025-08-30T05:32:20.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-29T00:00:00+00:00 [queued]>
[2025-08-30T05:32:20.125+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-30T05:32:20.271+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): daily_sales> on 2025-08-29 00:00:00+00:00
[2025-08-30T05:32:20.311+0000] {standard_task_runner.py:63} INFO - Started process 5121 to run task
[2025-08-30T05:32:20.321+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'daily_sales', 'scheduled__2025-08-29T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpdvrotght']
[2025-08-30T05:32:20.325+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask daily_sales
[2025-08-30T05:32:20.415+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-30T05:32:20.657+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-29T00:00:00+00:00 [running]> on host 6aba05baf296
[2025-08-30T05:32:21.223+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='daily_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-29T00:00:00+00:00'
[2025-08-30T05:32:21.233+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-30T05:32:21.271+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-30T05:32:21.274+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** psql -h postgres -U *** -d *** -f /opt/***/sql/daily_sales.sql']
[2025-08-30T05:32:21.314+0000] {subprocess.py:86} INFO - Output:
[2025-08-30T05:32:21.983+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:4: NOTICE:  table "daily_sales" does not exist, skipping
[2025-08-30T05:32:21.986+0000] {subprocess.py:93} INFO - DROP TABLE
[2025-08-30T05:32:21.987+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:16: ERROR:  relation "transactions" does not exist
[2025-08-30T05:32:21.988+0000] {subprocess.py:93} INFO - LINE 7: FROM transactions
[2025-08-30T05:32:21.994+0000] {subprocess.py:93} INFO -              ^
[2025-08-30T05:32:21.995+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:19: ERROR:  relation "daily_sales" does not exist
[2025-08-30T05:32:22.002+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:22: ERROR:  relation "daily_sales" does not exist
[2025-08-30T05:32:22.003+0000] {subprocess.py:93} INFO - LINE 1: SELECT * FROM daily_sales ORDER BY sales_date LIMIT 10;
[2025-08-30T05:32:22.004+0000] {subprocess.py:93} INFO -                       ^
[2025-08-30T05:32:22.027+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-30T05:32:22.032+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-30T05:32:22.166+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecommerce_pipeline, task_id=daily_sales, run_id=scheduled__2025-08-29T00:00:00+00:00, execution_date=20250829T000000, start_date=20250830T053220, end_date=20250830T053222
[2025-08-30T05:32:22.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-30T05:32:22.472+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
